<?php
/**
 * PayoutMethodMobileProviderEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  BitPesa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BitPesa API
 *
 * Reference documentation for the BitPesa API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BitPesa\Model;
use \BitPesa\ObjectSerializer;

/**
 * PayoutMethodMobileProviderEnum Class Doc Comment
 *
 * @category Class
 * @description The movile provider of the recipient:  - &#x60;orange&#x60;: Orange - &#x60;tigo&#x60;: Tigo
 * @package  BitPesa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PayoutMethodMobileProviderEnum
{
    /**
     * Possible values of this enum
     */
    const ORANGE = 'orange';
    const TIGO = 'tigo';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ORANGE,
            self::TIGO,
        ];
    }
}


