<?php
/**
 * PayoutMethodBankAccountTypeEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  BitPesa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BitPesa API
 *
 * Reference documentation for the BitPesa API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BitPesa\Model;
use \BitPesa\ObjectSerializer;

/**
 * PayoutMethodBankAccountTypeEnum Class Doc Comment
 *
 * @category Class
 * @description The type of the bank account:  - &#x60;10&#x60;: Savings account - &#x60;20&#x60;: Current account
 * @package  BitPesa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PayoutMethodBankAccountTypeEnum
{
    /**
     * Possible values of this enum
     */
    const _10 = '10';
    const _20 = '20';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_10,
            self::_20,
        ];
    }
}


