<?php
/**
 * PaginationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BitPesa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BitPesa API
 *
 * Reference documentation for the BitPesa API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BitPesa;

use PHPUnit\Framework\TestCase;

/**
 * PaginationTest Class Doc Comment
 *
 * @category    Class
 * @description Pagination
 * @package     BitPesa
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PaginationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Pagination"
     */
    public function testPagination()
    {
    }

    /**
     * Test attribute "current_page"
     */
    public function testPropertyCurrentPage()
    {
    }

    /**
     * Test attribute "next_page"
     */
    public function testPropertyNextPage()
    {
    }

    /**
     * Test attribute "prev_page"
     */
    public function testPropertyPrevPage()
    {
    }

    /**
     * Test attribute "total_pages"
     */
    public function testPropertyTotalPages()
    {
    }

    /**
     * Test attribute "total_count"
     */
    public function testPropertyTotalCount()
    {
    }
}
