<?php
/**
 * WebhookLogMetadataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BitPesa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BitPesa API
 *
 * Reference documentation for the BitPesa API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BitPesa;

use PHPUnit\Framework\TestCase;

/**
 * WebhookLogMetadataTest Class Doc Comment
 *
 * @category    Class
 * @description WebhookLogMetadata
 * @package     BitPesa
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WebhookLogMetadataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WebhookLogMetadata"
     */
    public function testWebhookLogMetadata()
    {
    }

    /**
     * Test attribute "params"
     */
    public function testPropertyParams()
    {
    }

    /**
     * Test attribute "event"
     */
    public function testPropertyEvent()
    {
    }

    /**
     * Test attribute "instance_id"
     */
    public function testPropertyInstanceId()
    {
    }

    /**
     * Test attribute "instance_type"
     */
    public function testPropertyInstanceType()
    {
    }

    /**
     * Test attribute "attempt_id"
     */
    public function testPropertyAttemptId()
    {
    }

    /**
     * Test attribute "tries"
     */
    public function testPropertyTries()
    {
    }

    /**
     * Test attribute "request"
     */
    public function testPropertyRequest()
    {
    }

    /**
     * Test attribute "response"
     */
    public function testPropertyResponse()
    {
    }

    /**
     * Test attribute "app_id"
     */
    public function testPropertyAppId()
    {
    }

    /**
     * Test attribute "api_key_id"
     */
    public function testPropertyApiKeyId()
    {
    }
}
