<?php
/**
 * CurrencyInfoApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BitPesa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BitPesa API
 *
 * Reference documentation for the BitPesa API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BitPesa;

use \BitPesa\Configuration;
use \BitPesa\ApiException;
use \BitPesa\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CurrencyInfoApiTest Class Doc Comment
 *
 * @category Class
 * @package  BitPesa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CurrencyInfoApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for infoCurrencies
     *
     * Getting a list of possible requested currencies.
     *
     */
    public function testInfoCurrencies()
    {
    }

    /**
     * Test case for infoCurrenciesIn
     *
     * Getting a list of possible input currencies.
     *
     */
    public function testInfoCurrenciesIn()
    {
    }

    /**
     * Test case for infoCurrenciesOut
     *
     * Getting a list of possible output currencies.
     *
     */
    public function testInfoCurrenciesOut()
    {
    }
}
