<?php
/**
 * RecipientsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BitPesa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BitPesa API
 *
 * Reference documentation for the BitPesa API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BitPesa;

use \BitPesa\Configuration;
use \BitPesa\ApiException;
use \BitPesa\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RecipientsApiTest Class Doc Comment
 *
 * @category Class
 * @package  BitPesa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RecipientsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteRecipient
     *
     * Cancelling a recipient.
     *
     */
    public function testDeleteRecipient()
    {
    }

    /**
     * Test case for getRecipients
     *
     * Getting a list of recipients with filtering.
     *
     */
    public function testGetRecipients()
    {
    }

    /**
     * Test case for patchRecipient
     *
     * Updating a recipient.
     *
     */
    public function testPatchRecipient()
    {
    }
}
