<?php
/**
 * TransactionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BitPesa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BitPesa API
 *
 * Reference documentation for the BitPesa API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BitPesa;

use \BitPesa\Configuration;
use \BitPesa\ApiException;
use \BitPesa\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TransactionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  BitPesa
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransactionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for calculateTransactions
     *
     * Calculates transaction amounts for a transaction payload.
     *
     */
    public function testCalculateTransactions()
    {
    }

    /**
     * Test case for getTransaction
     *
     * Fetch a single transaction.
     *
     */
    public function testGetTransaction()
    {
    }

    /**
     * Test case for getTransactions
     *
     * Get a list of transactions.
     *
     */
    public function testGetTransactions()
    {
    }

    /**
     * Test case for payinTransaction
     *
     * Creates a fake payin for transaction.
     *
     */
    public function testPayinTransaction()
    {
    }

    /**
     * Test case for payoutTransaction
     *
     * Creates a fake payout for transaction.
     *
     */
    public function testPayoutTransaction()
    {
    }

    /**
     * Test case for postTransactions
     *
     * Creates a new transaction.
     *
     */
    public function testPostTransactions()
    {
    }

    /**
     * Test case for validateTransactions
     *
     * Validates a transaction payload.
     *
     */
    public function testValidateTransactions()
    {
    }
}
